parameters:
 - name: deploy
   type: boolean
   default: false

jobs:
  - job: Build
    displayName: "Build and Publish"
    steps:
      - ${{ if eq(parameters.deploy,true) }}:
        - task: LambdaNETCoreDeploy@1
          displayName: Deploy Lamdba Function              
          inputs:
            awsCredentials: 'AWS Personal'
            regionName: 'us-east-2'
            command: 'deployFunction'
            packageOnly: false
            lambdaProjectPath: '$(Build.SourcesDirectory)/KidproblemService/KidproblemService/KidproblemService.csproj'
            functionName: 'kidproblem'
            functionRole: 'inforcentralrole'
            functionHandler: 'KidproblemService'
            functionMemory: 256
            functionTimeout: 300
        - task: CopyFiles@2
          displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
          inputs:
            Contents: |
              $(Build.SourcesDirectory)/KidproblemService/KidproblemService/bin/Release/**/KidproblemService.zip
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - ${{else}}:
        - task: DotNetCoreCLI@2
          displayName: "Publish services"
          inputs:
            command: "publish"
            publishWebProjects: false
            projects: "$(Build.SourcesDirectory)/KidproblemService/KidproblemService/KidproblemService.csproj"
            arguments: "--configuration Release --output $(Build.BinariesDirectory)"
            zipAfterPublish: false
            workingDirectory: "$(Build.SourcesDirectory)/KidproblemService/KidproblemService"
        - task: ArchiveFiles@2
          displayName: "Archive service files"
          inputs:
            rootFolderOrFile: "$(Build.BinariesDirectory)"
            includeRootFolder: false
            archiveType: "zip"
            archiveFile: "$(Build.ArtifactStagingDirectory)/Services.zip"
            replaceExistingArchive: true

      - task: Npm@1
        displayName: Install Angular packages
        inputs:
          command: "ci"
          workingDir: "$(Build.SourcesDirectory)/kidproblem-client"

      - task: PowerShell@2
        displayName: Modify Build Number
        inputs:
          targetType: "inline"
          script: |
            $TARGETDIR = "$(Build.SourcesDirectory)/kidproblem-client/src/environments/environment.prod.ts"
            $BUILDNUM = "$env:BUILD_BUILDNUMBER"
            (Get-Content $TARGETDIR).replace('#BuildNumber#', "$BUILDNUM") | Set-Content $TARGETDIR
          errorActionPreference: "continue"

      - task: Npm@1
        displayName: "Build Angular UI"
        inputs:
          command: "custom"
          workingDir: "$(Build.SourcesDirectory)/kidproblem-client"
          customCommand: "run-script buildprod"

      # - task: PowerShell@2
      #   displayName: Rename Angular Artifacts
      #   inputs:
      #     targetType: "inline"
      #     script: |
      #         $path = "$(Build.SourcesDirectory)/kidproblem-client/dist/kidproblem-client"
      #         Get-ChildItem -Path $path -Filter *.* | ForEach-Object {
      #             $newName = $_.Name -replace '\.[a-z0-9]{16}', ''
      #             Rename-Item -Path $_.FullName -NewName $newName
      #         }
      #         $file = "$path/index.html"
      #         (Get-Content -Path $file ) -replace '\.[a-z0-9]{16}', '' | Set-Content -Path $file
      #     errorActionPreference: "continue"    

      - ${{ if eq(parameters.deploy,true) }}:
        - task: S3Upload@1
          displayName: Upload Angular App to S3
          continueOnError: true
          inputs:
            awsCredentials: 'AWS Personal'
            regionName: 'us-east-2'
            bucketName: 'kidproblem.nowsuncorp.com'
            sourceFolder: '$(Build.SourcesDirectory)/kidproblem-client/dist'
            globExpressions: '**'                       

      - task: ArchiveFiles@2
        displayName: Archive client files
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)/kidproblem-client/dist
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/Client.zip"
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        displayName: "Publish services and client files"
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "ReleaseFiles"
          publishLocation: "Container"
