import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Validators, FormBuilder, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { Problem } from '@app/_models';
import { ProblemService } from '@app/_services';
import { MessageService } from '@app/_services/message.service';
import { DisplayMessages } from '@app/_constants';
import { BehaviorSubject } from 'rxjs';
import { MatButtonModule } from '@angular/material/button';
import { MathDirective } from '../../../math/math.directive';
import { MatDividerModule } from '@angular/material/divider';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatCardModule } from '@angular/material/card';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { NgIf } from '@angular/common';

@Component({
  selector: 'app-problem-editor',
  templateUrl: './problem-editor.component.html',
  styleUrls: ['./problem-editor.component.css'],
  standalone: true,
  imports: [NgIf, MatProgressBarModule, ReactiveFormsModule, MatCardModule, MatFormFieldModule, MatInputModule, MatCheckboxModule, MatDividerModule, MathDirective, MatButtonModule]
})
export class ProblemEditorComponent implements OnInit {

  @Input({ alias: 'problem-title' }) problemTitle$ = new BehaviorSubject<string>('');
  @Output() created = new EventEmitter<string>();
  @Output() deleted = new EventEmitter<boolean>();
  @Output() changed = new EventEmitter<boolean>();

  isLoading: boolean;
  problem: Problem;
  messageTexts = DisplayMessages;
  problemEditorForm: FormGroup;
  previewProblemText: string;
  previewSolutionText: string;
  isNew = false;

  constructor(
    private problemService: ProblemService,
    private messageService: MessageService,
    private formBuilder: FormBuilder
  ) { }

  ngOnInit() {
    this.problemTitle$.subscribe(
      problemTitle => {
        this.isLoading = true;
        this.getProblem(problemTitle);
      }
    );
  }

  private getProblem(id: string) {
    if (id) {
      this.isNew = false;
      this.problemService.getProblem(id).then(
        data => {
          if (data != null) {
            this.problem = data;
            this.createFormGroup();
          } else {
            this.messageService.add(`${this.messageTexts.cannotRetrieveRecord} ${id}.`);
            this.problem = null;
          }
          this.isLoading = false;
        }
      );

    } else {
      // get a new Problem
      this.isNew = true;
      this.problem = {
        ProblemCategory: null,
        ProblemYear: null,
        ProblemTitle: null,
        ProblemNumber: null,
        ProblemText: null,
        ProblemAnswer: null,
        ProblemTags: null,
        IsStaging: true,
        SolutionText: null,
        AnswerOptions: null
      };
      this.createFormGroup();
    }
  }

  private createFormGroup(): void {
    const f = this.formBuilder.group({
      problemCategory: [this.problem.ProblemCategory, Validators.required],
      problemYear: [this.problem.ProblemYear, Validators.required],
      problemTitle: this.problem.ProblemTitle,
      problemNumber: [this.problem.ProblemNumber, Validators.required],
      problemText: [this.problem.ProblemText, Validators.required],
      problemAnswer: this.problem.ProblemAnswer,
      problemTags: (this.problem.ProblemTags || []).join(','),
      isStaging: this.problem.IsStaging,
      solutionText: this.problem.SolutionText,
      answerOptions: this.problem.AnswerOptions
    });

    f.valueChanges.subscribe(() => {
      this.changed.emit(true);
      // ProblemTitle is generated by the application
      if (this.isNew) {
        const category = this.problemEditorForm.get('problemCategory').value;
        const year = this.problemEditorForm.get('problemYear').value;
        const number = this.problemEditorForm.get('problemNumber').value;
        if (category && year && number) {
          const problemTitle = `${category}-${year}-${number.padStart(3, '0')}`;
          this.problemEditorForm.get('problemTitle').setValue(problemTitle, { emitEvent: false });
        }
      }
    });

    this.problemEditorForm = f;
  }

  private getValuesFromForm(): Problem {
    const problem = new Problem();
    problem.ProblemCategory = this.problemEditorForm.get('problemCategory').value;
    problem.ProblemYear = this.problemEditorForm.get('problemYear').value;
    problem.ProblemTitle = this.problemEditorForm.get('problemTitle').value;
    problem.ProblemNumber = this.problemEditorForm.get('problemNumber').value;
    problem.ProblemText = this.problemEditorForm.get('problemText').value;
    problem.ProblemAnswer = this.problemEditorForm.get('problemAnswer').value;
    problem.ProblemTags = (this.problemEditorForm.get('problemTags').value || '').split(',');
    problem.IsStaging = this.problemEditorForm.get('isStaging').value;
    problem.SolutionText = this.problemEditorForm.get('solutionText').value;
    problem.AnswerOptions = this.problemEditorForm.get('answerOptions').value;
    return problem;
  }

  save(): void {
    if (!this.problemEditorForm.valid) {
      this.messageService.add(this.messageTexts.invalidFormData);
      return;
    }

    if (!window.confirm(this.messageTexts.confirmSubmit)) {
      return;
    }

    const problem = this.getValuesFromForm();
    if (this.isNew) {
      this.problemService.createProblem(problem).then(data => this.handleSaveResponse(data));
    } else {
      this.problemService.updateProblem(problem).then(data => this.handleSaveResponse(data));
    }

  }

  delete(): void {
    if (this.isNew || !window.confirm(this.messageTexts.confirmDelete)) {
      return;
    }
    this.problemService.deleteProblem(this.problem.ProblemTitle).then(
      data => {
        if (data != null && data.IsSuccessful) {
          this.messageService.openSnackBar('Record is deleted');
          this.deleted.emit(true);
        } else {
          this.messageService.openSnackBar(`${this.messageTexts.deleteFailed}.`);
          this.messageService.add(`${this.messageTexts.deleteFailed}.`);
        }
      }
    );
  }

  previewText() {
    this.previewProblemText = this.problemEditorForm.get('problemText').value;
    this.previewSolutionText = this.problemEditorForm.get('solutionText').value;
  }

  onSolutionTextBlur(event: Event) {
    const textValue = (event.target as HTMLTextAreaElement).value;
    if(!textValue){
      return;
    }
    
    const lines = textValue.split(/\r?\n/);
    let valueChanged = false;
    lines.forEach((text, i) => {
      let line = text;
      // add <br/> to the end of line
      if (!line.trim().endsWith('<br/>')) {
        line += '<br/>';
      }
      // add <br/> between \] and \[
      line = line.replace(/\\\]\[\\\]/g, '\\]<br/>\r\n\\[');

      // if the line contains "<letters or :,;.>\[", add "<br/>" before "\["
      line = line.replace(/([a-zA-Z,:;.])\\\[/g, '$1<br/>\r\n\\[');

      // if the line contains "\]<letters>", add "<br/>" after "\]"
      line = line.replace(/\\\]([a-zA-Z])/g, '\\]<br/>\r\n$1');

      // replace "\frac" with "\dfrac"
      line = line.replace('\\frac', '\\dfrac');

      if (line != text) {
        lines[i] = line;
        valueChanged = true;
      }
      
    });

    if (valueChanged){
      const newValue = lines.join('\r\n');
      this.problemEditorForm.get('solutionText').patchValue(newValue);
    }
    
  }

  private handleSaveResponse(data: Problem) {
    let isSuccessful = false;
    const messages: string[] = [];

    if (data != null) {
      isSuccessful = data.IsSuccessful;
      messages.push(data.ReturnResult);
      this.problem = data;
    }

    if (isSuccessful) {
      this.messageService.openSnackBar(`${this.messageTexts.saveSuccessful}`);
      this.problemEditorForm.markAsPristine();
      this.changed.emit(false);
      if (this.isNew) {
        this.created.emit(this.problem.ProblemTitle);
      }
    } else {
      const message = messages.join(' ');
      this.messageService.openSnackBar(`${this.messageTexts.saveFailed}`);
      this.messageService.add(`${this.messageTexts.saveFailed}: ${message}`);
    }
  }

}
