export const DisplayMessages = {
    invalidFormat: ' invalid format ',
    required: ' required ',
    btnReturn: 'Back',
    btnSave: 'Save',
    btnDelete: 'Delete',
    confirmSubmit: 'Do you want to save the record?',
    confirmDelete: 'Do you want to delete the record?',
    invalidFormData: 'Invalid form data',
    cannotRetrieveRecord: 'Cannot retrieve the record',
    saveSuccessful: 'Save Successful',
    saveFailed: 'Failed to save',
    deleteFailed: 'Failed to delete',
    foundDuplicateRecords: 'Cannot save duplicate record',
    labelUserName: 'User Name',
    labelPassword: 'Password',
    labelLogin: 'Login',
    warningUnansweredProblem: 'There is unanswered problem. Are you sure to continue?',
    warningUnsavedChanges: 'There is unsaved change. Are you sure to continue?',
    onlyForChild: 'Only Child user can start an Assignment.',
    common: {
        NoRecord: 'No record found',
        SelectAll: 'Select All',
        Export: 'Export data',
        Filter: 'Filter',
        CannotRetrieveRecord: 'Cannot retrieve record',
        InvalidFormData: 'Invalid form data',
        Save: 'Save',
        Delete: 'Delete',
        Cancel: 'Cancel',
        Select: 'Select',
        ConfirmSubmit: 'Are you sure to save?',
        ConfirmDelete: 'Are you sure to delete?',
        SaveSuccessful: 'Save Successful',
        DeleteSuccessful: 'Record is deleted',
        SaveFailed: 'Failed to save',
        DeleteFailed: 'Failed to delete',
        Edit: 'Edit',
        View: 'View',
        Browse: 'Browse',
        Create: 'Create',
        Search: 'Search',
        EnableEdit: 'Enable Edit',
        ExitEdit: 'Exit Edit',
        Required: 'Require',
        WarningUnsavedChanges: 'Form has been changed. Are you sure to continue without saving?',
        Keyword: 'Keyword',
        LoadMore: 'Load more data',
        DisplayNames: {
            Status: 'Status',
            Memo: 'Memo',
        }
    },
    auth: {
        ChangePassword: 'Change Password',
        Logout: 'Logout',
        Login: 'Sign In',
        Username: 'User Name',
        Password: 'Password',
        ForgetPassword: 'Forget Password',
        SetPasswordFirstLogin: 'This is the first time login. Please set a new password.',
        ConfirmPassword: 'Confirm Password',
        ConfirmNewPassword: 'Confirm New Password',
        ConfirmationCode: 'Confirmation Code (Check your email)',
        SavePassword: 'Save Password',
        ErrorConfirmPassword: 'Please enter password and ensure passwords entered are the same',
        SuccessfulChangePassword: 'Password has been updated. Please use your new password to sign in.',
        FailChangePassword: 'Failed to update password',
        ErrorRequireUsername: 'User Name is required',
        OldPassword: 'Old Password',
        NewPassword: 'New Password'
    }
};
