name: '$(application.version)_$(Date:yyyMMdd)$(Rev:.rr)'

trigger: 
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md 
    - .azure-pipelines/**/*.yml   

pool:
  vmImage: windows-latest
  # vmImage: 'ubuntu-latest'


parameters:
 - name: deploy
   displayName: Deploy to AWS
   type: boolean
   default: true
 - name: run_test
   displayName: Run Tests
   type: boolean
   default: false   

variables:
  buildConfiguration: 'Release'
  vmImageName: 'ubuntu-latest'
  application.version: '2.0.0'

stages:

- stage: CI
  displayName: 'Continuous Integration'
  condition: |
      in(variables['Build.Reason'], 'PullRequest')
  jobs:
    - job: staging
      steps:
      - template: steps/build-steps.yml
        parameters:
          deploy: false
          runTest: false
          production: false

- stage: Build
  displayName: 'Staging'
  dependsOn: []
  condition: |
    ne(variables['Build.Reason'], 'PullRequest')
  jobs:
    - job: Staging
      steps:
      - template: steps/build-steps.yml
        parameters:
          deploy: ${{parameters.deploy}}
          runTest: ${{parameters.run_test}}
          production: false
          lambdaFunctionName: kidproblemdev
          s3BucketName: kidproblemdev.nowsuncorp.com

- ${{ if eq(parameters.deploy,true) }}:
  - stage: Production
    displayName: 'Production'
    dependsOn: 
      - Build
    condition: |
      ne(variables['Build.Reason'], 'PullRequest')
    jobs:
      - deployment: Production
        environment: kidproblem-prod
        strategy:
          runOnce:
            deploy:
              steps:          
              - download: none
              - checkout: self
              - template: steps/build-steps.yml
                parameters:
                  deploy: true
                  runTest: false
                  production: true
                  lambdaFunctionName: kidproblem
                  s3BucketName: kidproblem.nowsuncorp.com        

